




module.exports = {
    Valhallan: "https://brawlhalla.wiki.gg/images/1/1c/Banner_Rank_Valhallan.png",
    Diamond: "https://brawlhalla.wiki.gg/images/4/46/Banner_Rank_Diamond.png",
    Platinum: "https://brawlhalla.wiki.gg/images/6/6e/Banner_Rank_Platinum.png",
    Gold: "https://brawlhalla.wiki.gg/images/6/69/Banner_Rank_Gold.png",
    Silver: "https://brawlhalla.wiki.gg/images/5/5c/Banner_Rank_Silver.png",
    Bronze:"https://brawlhalla.wiki.gg/images/a/a6/Banner_Rank_Bronze.png",
    Tin: "https://brawlhalla.wiki.gg/images/e/e1/Banner_Rank_Tin.png",

    ada: "https://brawlhalla.wiki.gg/images/f/f9/Ada.png",
    arcadia: "https://brawlhalla.wiki.gg/images/9/90/Arcadia.png",
    artemis: "https://brawlhalla.wiki.gg/images/d/d2/Artemis.png",
    asuri: "https://brawlhalla.wiki.gg/images/e/e5/Asuri.png",
    azoth: "https://brawlhalla.wiki.gg/images/c/c7/Azoth.png",
    barraza: "https://brawlhalla.wiki.gg/images/6/6f/Barraza.png",
    brynn: "https://brawlhalla.wiki.gg/images/3/35/Brynn.png",
    caspian: "https://brawlhalla.wiki.gg/images/3/34/Caspian.png",
    cassidy: "https://brawlhalla.wiki.gg/images/a/a2/Cassidy.png",
    cross: "https://brawlhalla.wiki.gg/images/4/4e/Cross.png",
    diana: "https://brawlhalla.wiki.gg/images/5/5f/Diana.png",
    dusk: "https://brawlhalla.wiki.gg/images/5/5d/Dusk.png",
    ember: "https://brawlhalla.wiki.gg/images/3/38/Ember.png",
    ezio: "https://brawlhalla.wiki.gg/images/f/f7/Ezio.png",
    fait: "https://brawlhalla.wiki.gg/images/6/67/Fait.png",
    gnash: "https://brawlhalla.wiki.gg/images/7/7f/Gnash.png",
    hattori: "https://brawlhalla.wiki.gg/images/3/34/Hattori.png",
    imugi: "https://brawlhalla.wiki.gg/images/b/b4/Imugi.png",
    isaiah: "https://brawlhalla.wiki.gg/images/e/ed/Isaiah.png",
    jaeyun: "https://brawlhalla.wiki.gg/images/2/25/Jaeyun.png",
    jhala: "https://brawlhalla.wiki.gg/images/9/9a/Jhala.png",
    jiro: "https://brawlhalla.wiki.gg/images/5/5a/Jiro.png",
    kaya: "https://brawlhalla.wiki.gg/images/9/97/Kaya.png",
    "king zuva": "https://brawlhalla.wiki.gg/images/c/c6/King_Zuva.png",
    koji: "https://brawlhalla.wiki.gg/images/f/f2/Koji.png",
    kor: "https://brawlhalla.wiki.gg/images/9/96/Kor.png",
    "lin fei": "https://brawlhalla.wiki.gg/images/8/81/Lin_Fei.png",
    loki: "https://brawlhalla.wiki.gg/images/f/fe/Loki.png",
    lucien: "https://brawlhalla.wiki.gg/images/1/1e/Lucien.png",
    magyar: "https://brawlhalla.wiki.gg/images/2/2e/Magyar.png",
    mako: "https://brawlhalla.wiki.gg/images/a/a6/Mako.png",
    mirage: "https://brawlhalla.wiki.gg/images/f/fb/Mirage.png",
    mordex: "https://brawlhalla.wiki.gg/images/2/2d/Mordex.png",
    munin: "https://brawlhalla.wiki.gg/images/5/52/Munin.png",
    queen_nai: "https://brawlhalla.wiki.gg/images/e/ea/Queen_Nai.png",
    nix: "https://brawlhalla.wiki.gg/images/0/0f/Nix.png",
    onyx: "https://brawlhalla.wiki.gg/images/f/fb/Onyx.png",
    orion: "https://brawlhalla.wiki.gg/images/0/0e/Orion.png",
    petra: "https://brawlhalla.wiki.gg/images/9/93/Petra.png",
    ragnir: "https://brawlhalla.wiki.gg/images/1/18/Ragnir.png",
    rayman: "https://brawlhalla.wiki.gg/images/c/c1/Rayman.png",
    red_raptor: "https://brawlhalla.wiki.gg/images/0/02/Red_Raptor.png",
    reno: "https://brawlhalla.wiki.gg/images/5/54/Reno.png",
    scarlet: "https://brawlhalla.wiki.gg/images/7/7a/Scarlet.png",
    sentinel: "https://brawlhalla.wiki.gg/images/9/91/Sentinel.png",
    seven: "https://brawlhalla.wiki.gg/images/f/fe/Seven.png",
    sidra: "https://brawlhalla.wiki.gg/images/e/e6/Sidra.png",
    sir_roland: "https://brawlhalla.wiki.gg/images/6/6f/Sir_Roland.png",
    teros: "https://brawlhalla.wiki.gg/images/f/ff/Teros.png",
    tezca: "https://brawlhalla.wiki.gg/images/0/0c/Tezca.png",
    thatch: "https://brawlhalla.wiki.gg/images/5/51/Thatch.png",
    thea: "https://brawlhalla.wiki.gg/images/3/3c/Thea.png",
    thor: "https://brawlhalla.wiki.gg/images/0/0b/Thor.png",
    ulgrim: "https://brawlhalla.wiki.gg/images/3/33/Ulgrim.png",
    val: "https://brawlhalla.wiki.gg/images/f/fc/Val.png",
    vector: "https://brawlhalla.wiki.gg/images/2/27/Vector.png",
    vivi: "https://brawlhalla.wiki.gg/images/4/4d/Vivi.png",
    volkov: "https://brawlhalla.wiki.gg/images/2/25/Volkov.png",
    lord_vraxx: "https://brawlhalla.wiki.gg/images/6/66/Lord_Vraxx.png",
    wu_shang: "https://brawlhalla.wiki.gg/images/5/5e/Wu_Shang.png",
    xull: "https://brawlhalla.wiki.gg/images/6/6c/Xull.png",
    yumiko: "https://brawlhalla.wiki.gg/images/1/1e/Yumiko.png",
    zariel: "https://brawlhalla.wiki.gg/images/f/f4/Zariel.png",
    

}