import unarmed from '../images/unarmed.webp';
import XP from '../images/XP.png';
import SuicideIcon from '../images/deaths-icon.png';
export const ranks = {    Valhallan: "https://brawlhalla.wiki.gg/images/1/1c/Banner_Rank_Valhallan.png",
    Diamond: "https://brawlhalla.wiki.gg/images/4/46/Banner_Rank_Diamond.png",
    Platinum: "https://brawlhalla.wiki.gg/images/6/6e/Banner_Rank_Platinum.png",
    Gold: "https://brawlhalla.wiki.gg/images/6/69/Banner_Rank_Gold.png",
    Silver: "https://brawlhalla.wiki.gg/images/5/5c/Banner_Rank_Silver.png",
    Bronze:"https://brawlhalla.wiki.gg/images/a/a6/Banner_Rank_Bronze.png",
    Tin: "https://brawlhalla.wiki.gg/images/e/e1/Banner_Rank_Tin.png",
    Diamond_Frame:  "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/3f/Loading_Diamond.png",
    Platinum_Frame: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/1/18/Loading_Platinum.png",
    Gold_Frame: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/53/Loading_Gold.png",
    Default_Frame: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/38/Loading_Default.png",
    Valhalla_Frame: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/7/72/Loading_Valhallan.png"
    }


    
    export const legendImgs = { ada: "https://brawlhalla.wiki.gg/images/f/f9/Ada.png",
    arcadia: "https://brawlhalla.wiki.gg/images/9/90/Arcadia.png",
    artemis: "https://brawlhalla.wiki.gg/images/d/d2/Artemis.png",
    asuri: "https://brawlhalla.wiki.gg/images/e/e5/Asuri.png",
    azoth: "https://brawlhalla.wiki.gg/images/c/c7/Azoth.png",
    barraza: "https://brawlhalla.wiki.gg/images/6/6f/Barraza.png",
    brynn: "https://brawlhalla.wiki.gg/images/3/35/Brynn.png",
    bodvar: "https://brawlhalla.wiki.gg/images/e/e2/Bodvar.png",
    caspian: "https://brawlhalla.wiki.gg/images/3/34/Caspian.png",
    cassidy: "https://brawlhalla.wiki.gg/images/a/a2/Cassidy.png",
    cross: "https://brawlhalla.wiki.gg/images/4/4e/Cross.png",
    diana: "https://brawlhalla.wiki.gg/images/5/5f/Diana.png",
    dusk: "https://brawlhalla.wiki.gg/images/5/5d/Dusk.png",
    ember: "https://brawlhalla.wiki.gg/images/3/38/Ember.png",
    ezio: "https://brawlhalla.wiki.gg/images/f/f7/Ezio.png",
    fait: "https://brawlhalla.wiki.gg/images/6/67/Fait.png",
    gnash: "https://brawlhalla.wiki.gg/images/7/7f/Gnash.png",
    hattori: "https://brawlhalla.wiki.gg/images/3/34/Hattori.png",
    imugi: "https://brawlhalla.wiki.gg/images/b/b4/Imugi.png",
    isaiah: "https://brawlhalla.wiki.gg/images/e/ed/Isaiah.png",
    jaeyun: "https://brawlhalla.wiki.gg/images/2/25/Jaeyun.png",
    jhala: "https://brawlhalla.wiki.gg/images/9/9a/Jhala.png",
    jiro: "https://brawlhalla.wiki.gg/images/5/5a/Jiro.png",
    kaya: "https://brawlhalla.wiki.gg/images/9/97/Kaya.png",
    king_zuva: "https://brawlhalla.wiki.gg/images/c/c6/King_Zuva.png",
    koji: "https://brawlhalla.wiki.gg/images/f/f2/Koji.png",
    kor: "https://brawlhalla.wiki.gg/images/9/96/Kor.png",
    lin_fei: "https://brawlhalla.wiki.gg/images/8/81/Lin_Fei.png",
    loki: "https://brawlhalla.wiki.gg/images/f/fe/Loki.png",
    lucien: "https://brawlhalla.wiki.gg/images/1/1e/Lucien.png",
    magyar: "https://brawlhalla.wiki.gg/images/2/2e/Magyar.png",
    mako: "https://brawlhalla.wiki.gg/images/a/a6/Mako.png",
    mirage: "https://brawlhalla.wiki.gg/images/f/fb/Mirage.png",
    mordex: "https://brawlhalla.wiki.gg/images/2/2d/Mordex.png",
    munin: "https://brawlhalla.wiki.gg/images/5/52/Munin.png",
    queen_nai: "https://brawlhalla.wiki.gg/images/e/ea/Queen_Nai.png",
    nix: "https://brawlhalla.wiki.gg/images/0/0f/Nix.png",
    onyx: "https://brawlhalla.wiki.gg/images/f/fb/Onyx.png",
    orion: "https://brawlhalla.wiki.gg/images/0/0e/Orion.png",
    petra: "https://brawlhalla.wiki.gg/images/9/93/Petra.png",
    priya: "https://brawlhalla.wiki.gg/images/d/d2/Priya.png",
    ragnir: "https://brawlhalla.wiki.gg/images/1/18/Ragnir.png",
    rayman: "https://brawlhalla.wiki.gg/images/c/c1/Rayman.png",
    red_raptor: "https://brawlhalla.wiki.gg/images/0/02/Red_Raptor.png",
    reno: "https://brawlhalla.wiki.gg/images/5/54/Reno.png",
    scarlet: "https://brawlhalla.wiki.gg/images/7/7a/Scarlet.png",
    sentinel: "https://brawlhalla.wiki.gg/images/9/91/Sentinel.png",
    seven: "https://brawlhalla.wiki.gg/images/f/fe/Seven.png",
    sidra: "https://brawlhalla.wiki.gg/images/e/e6/Sidra.png",
    sir_roland: "https://brawlhalla.wiki.gg/images/6/6f/Sir_Roland.png",
    teros: "https://brawlhalla.wiki.gg/images/f/ff/Teros.png",
    tezca: "https://brawlhalla.wiki.gg/images/0/0c/Tezca.png",
    thatch: "https://brawlhalla.wiki.gg/images/5/51/Thatch.png",
    thea: "https://brawlhalla.wiki.gg/images/3/3c/Thea.png",
    thor: "https://brawlhalla.wiki.gg/images/0/0b/Thor.png",
    ulgrim: "https://brawlhalla.wiki.gg/images/3/33/Ulgrim.png",
    val: "https://brawlhalla.wiki.gg/images/f/fc/Val.png",
    vector: "https://brawlhalla.wiki.gg/images/2/27/Vector.png",
    vivi: "https://brawlhalla.wiki.gg/images/4/4d/Vivi.png",
    volkov: "https://brawlhalla.wiki.gg/images/2/25/Volkov.png",
    lord_vraxx: "https://brawlhalla.wiki.gg/images/6/66/Lord_Vraxx.png",
    wu_shang: "https://brawlhalla.wiki.gg/images/5/5e/Wu_Shang.png",
    xull: "https://brawlhalla.wiki.gg/images/6/6c/Xull.png",
    yumiko: "https://brawlhalla.wiki.gg/images/1/1e/Yumiko.png",
    zariel: "https://brawlhalla.wiki.gg/images/f/f4/Zariel.png",
    
}
export const weaponImgs = {
    axe: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/d/d6/Axe_Icon.png",
    battle_boots: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/4/4e/Battle_Boots_Icon.png",
    blasters: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/a/a3/Blasters_Icon.png",
    bow:"https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/05/Bow_Icon.png",
    cannon: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/6/6b/Cannon_Icon.png",
    gauntlets: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/85/Gauntlets_Icon.png",
    grapple_hammer: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/4/4b/Grapple_Hammer_Icon.png",
    greatsword: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/7/7f/Greatsword_Icon.png",
    katars: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/97/Katars_Icon.png",
    orb: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/08/Orb_Icon.png",
    rocket_lance: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/9f/Rocket_Lance_Icon.png",
    scythe: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/e/ea/Scythe_Icon.png",
    spear: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/2/26/Spear_Icon.png",
    sword: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/32/Sword_Icon.png",
    boomerang: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/5d/Gadget_Boomerang.png",
    chakram: "https://brawlhalla.wiki.gg/images/thumb/2/21/Chakram_Icon.png/54px-Chakram_Icon.png",
    unarmed: unarmed
}

export const brawlhallaImgs = {
    logo: "https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/1chpPXELuOEA87USrEEpX3/1c84738efc62990e7051d2453feef59f/BRAWLHALLA_LOGO_LOCKUP_COLOR_BIGGER.png",
    lvl_50: "https://brawlhalla.wiki.gg/images/thumb/a/a3/Reward_Level_50_Icon.png/120px-Reward_Level_50_Icon.png",
    lvl_100: "https://brawlhalla.wiki.gg/images/thumb/a/a9/Reward_Level_100_Icon.png/120px-Reward_Level_100_Icon.png",
    damagedealt: "https://cdn2.iconfinder.com/data/icons/rpg-fantasy-game-skill-ui/512/game_skill_ui_knife_stab_damage-512.png",
    damagegadget: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/e/ea/Gadget_Bomb.png/",
    damagetaken: "https://cdn-icons-png.flaticon.com/512/7037/7037179.png",
    falls: "https://static.thenounproject.com/png/39793-200.png",
    ko: "https://www.svgrepo.com/show/320128/knockout.svg",
    xp: XP,
    "2v2": "https://cdn-icons-png.flaticon.com/512/3292/3292205.png",
    leader: "https://brawlhalla.wiki.gg/images/thumb/e/e5/Clans_Leader.png/120px-Clans_Leader.png",
    officer: "https://brawlhalla.wiki.gg/images/thumb/0/0d/Clans_Officer.png/120px-Clans_Officer.png",
    member: "https://brawlhalla.wiki.gg/images/thumb/e/e8/Clans_Member.png/120px-Clans_Member.png",
    recruit: "https://brawlhalla.wiki.gg/images/thumb/2/2b/Clans_Recruit.png/120px-Clans_Recruit.png",
    suicides: SuicideIcon

}
export const legendThumbnails = {   
    ada_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/ada.png",
    arcadia_thumbnail: "https://cms.brawlhalla.com/c/uploads/2022/03/a_Roster_Pose_FairyQueenM.png",
    artemis_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_SpaceHunterM.png",
    asuri_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_CatM.png",
    azoth_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_AzothM.png",
    barraza_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ApocM.png",
    bodvar_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/bodvar.png",
    brynn_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ValkyrieM.png",
    caspian_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ThiefM.png",
    cassidy_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/cassidy.png",
    cross_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_CrossM.png",
    diana_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_MonsterHunterM.png",
    dusk_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ElfwarM.png",
    ember_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ElfM.png",
    ezio_thumbnail: "https://cms.brawlhalla.com/c/uploads/2022/07/a_Roster_Pose_EzioM.png",
    fait_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_SpellwitchM.png",
    gnash_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/gnash.png",
    hattori_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/hattori.png",
    imugi_thumbnail: "https://cms.brawlhalla.com/c/uploads/2024/07/imgui-icon.png",
    isaiah_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_SoldierM.png",
    jaeyun_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_SellswordM.png",
    jhala_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_BarbarianM.png",
    jiro_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ShinobiM.png",
    kaya_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_InuitM-1.png",
    "king zuva_thumbnail": "https://cms.brawlhalla.com/c/uploads/2024/10/a_Roster_Pose_ZuvaM.png",
    koji_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_SamuraiM.png",
    kor_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_GolemM.png",
    "lin fei_thumbnail": "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_WuxiaM.png",
    loki_thumbnail: "https://cms.brawlhalla.com/c/uploads/2023/09/Loki_icon-1.png",
    lucien_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/lucien.png",
    magyar_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_GhostArmorM.png",
    mako_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ActualSharkM.png",
    mirage_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_AssassinM.png",
    mordex_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_WerewolfM.png",
    munin_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/12/a_Roster_Pose_BirdBardM.png",
    "queen nai_thumbnail": "https://cms.brawlhalla.com/c/uploads/2021/07/nai.png",
    nix_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ReaperM.png",
    onyx_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_GargoyleM.png",
    orion_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/orion.png",
    petra_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_RagefighterM.png",
    priya_thumbnail: "https://cms.brawlhalla.com/c/uploads/2025/01/Mobile-icon.png",
    ragnir_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_DragonM.png",
    rayman_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_RaymanM.png",
    "redraptor_thumbnail": "https://cms.brawlhalla.com/c/uploads/2023/06/a_Roster_Pose_SentaiM.png",
    reno_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_BountyHunterM.png",
    scarlet_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/scarlet.png",
    sentinel_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/sentinel.png",
    seven_thumbnail: "https://cms.brawlhalla.com/c/uploads/2023/12/roboengineer-rostericon.png",
    sidra_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_CorsairM.png",
    "sir roland_thumbnail": "https://cms.brawlhalla.com/c/uploads/2021/07/roland.png",
    teros_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/teros.png",
    tezca_thumbnail: "https://cms.brawlhalla.com/c/uploads/2022/12/a_Roster_Pose_LuchadorM.png",
    thatch_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/thatch.png",
    thea_thumbnail: "https://cms.brawlhalla.com/c/uploads/2023/03/a_Roster_Pose_SpeedsterM.png",
    thor_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ThorM.png",
    ulgrim_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_DwarfM.png",
    val_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ValM.png",
    vector_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ActualRobotM.png",
    vivi_thumbnail: "https://cms.brawlhalla.com/c/uploads/2024/08/a_Roster_Pose_ViviL.png",
    volkov_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_VampLordM.png",
    "lord vraxx_thumbnail": "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_VraxxM-1.png",
    "wu shang_thumbnail": "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_MonkM.png",
    xull_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_BruteM.png",
    yumiko_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_KitsuneM.png",
    zariel_thumbnail: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_CelestialM.png"
    
    }
    export const legendHeadshots = {   
        ada_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/2/20/SkinIcon_Ada_Classic.png",
        arcadia_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/c/cb/SkinIcon_Arcadia_Classic.png",
        artemis_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/5b/SkinIcon_Artemis_Classic.png",
        asuri_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/58/SkinIcon_Asuri_Classic.png",
        azoth_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/d/de/SkinIcon_Azoth_Classic.png",
        barraza_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/c/c5/SkinIcon_Barraza_Classic.png",
        bodvar_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/3c/SkinIcon_Bodvar_Classic.png",
        brynn_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/f/fb/SkinIcon_Brynn_Classic.png",
        caspian_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/5e/SkinIcon_Caspian_Classic.png",
        cassidy_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/87/SkinIcon_Cassidy_Classic.png",
        cross_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/a/a5/SkinIcon_Cross_Classic.png",
        diana_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/e/ec/SkinIcon_Diana_Classic.png",
        dusk_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/56/SkinIcon_Dusk_Classic.png",
        ember_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/51/SkinIcon_Ember_Classic.png",
        ezio_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/95/SkinIcon_Ezio_Classic.png",
        fait_headshot: "https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_SpellwitchM.png",
        gnash_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/32/SkinIcon_Gnash_Classic.png",
        hattori_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/a/a8/SkinIcon_Hattori_Classic.png",
        imugi_headshot: "https://cms.brawlhalla.com/c/uploads/2024/07/imgui-icon.png",
        isaiah_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/6/65/SkinIcon_Isaiah_Classic.png",
        jaeyun_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/b/b4/SkinIcon_Jaeyun_Classic.png",
        jhala_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/97/SkinIcon_Jhala_Classic.png",
        jiro_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/9b/SkinIcon_Jiro_Classic.png",
        kaya_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/8e/SkinIcon_Kaya_Classic.png",
        "king zuva_headshot": "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/f/fa/SkinIcon_Classic.png",
        koji_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/7/78/SkinIcon_Koji_Classic.png",
        kor_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/93/SkinIcon_Kor_Classic.png",
        "lin fei_headshot": "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/d/d2/SkinIcon_LinFei_Classic.png",
        loki_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/7/72/SkinIcon_Loki_Classic.png",
        lucien_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/6/6e/SkinIcon_Lucien_Classic.png",
        magyar_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/1/12/SkinIcon_Magyar_Classic.png",
        mako_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/8e/SkinIcon_Mako_Classic.png",
        mirage_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/d/d2/SkinIcon_Mirage_Classic.png",
        mordex_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/9/96/SkinIcon_Mordex_Classic.png",
        munin_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/4/4b/SkinIcon_Munin_Classic.png",
        "queen nai_headshot": "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/0f/SkinIcon_QueenNai_Classic.png",
        nix_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/f/f5/SkinIcon_Nix_Classic.png",
        onyx_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/c/cb/SkinIcon_Onyx_Classic.png",
        orion_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/0a/SkinIcon_Orion_Classic.png",
        petra_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/2/2a/SkinIcon_Petra_Classic.png",
        priya_headshot: "https://cms.brawlhalla.com/c/uploads/2025/01/Mobile-icon.png",
        ragnir_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/f/f4/SkinIcon_Ragnir_Classic.png",
        rayman_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/c/c7/SkinIcon_Rayman_Classic.png",
        "redraptor_headshot": "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/a/a5/SkinIcon_RedRaptor_Classic.png",
        reno_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/7/75/SkinIcon_Reno_Classic.png",
        scarlet_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/b/b4/SkinIcon_Scarlet_Classic.png",
        sentinel_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/87/SkinIcon_Sentinel_Classic.png",
        seven_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/b/b8/SkinIcon_Seven_Classic.png",
        sidra_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/1/19/SkinIcon_Sidra_Classic.png",
        "sir roland_headshot": "https://cms.brawlhalla.com/c/uploads/2021/07/roland.png",
        teros_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/58/SkinIcon_Teros_Classic.png",
        tezca_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/37/SkinIcon_Tezca_Classic.png",
        thatch_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/32/SkinIcon_Thatch_Classic.png",
        thea_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/82/SkinIcon_Thea_Classic.png",
        thor_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/02/SkinIcon_Thor_Classic.png",
        ulgrim_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/8/83/SkinIcon_Ulgrim_Classic.png",
        val_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/5/56/SkinIcon_Val_Classic.png",
        vector_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/a/a7/SkinIcon_Vector_Classic.png",
        vivi_headshot: "https://cms.brawlhalla.com/c/uploads/2024/08/a_Roster_Pose_ViviL.png",
        volkov_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/0d/SkinIcon_Volkov_Classic.png",
        "lord vraxx_headshot": "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/0/0b/SkinIcon_LordVraxx_Classic.png",
        "wu shang_headshot": "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/39/SkinIcon_WuShang_Classic.png",
        xull_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/3/3d/SkinIcon_Xull_Classic.png",
        yumiko_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/1/15/SkinIcon_Yumiko_Classic.png",
        zariel_headshot: "https://static.wikia.nocookie.net/brawlhalla_gamepedia/images/d/dc/SkinIcon_Zariel_Classic.png"
        
        }
